# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e367d76650f830013da770a4c459e8e880da56d6cb58afbfef012c19ba3daff22ae4064044e3eb4d122834cfa6670f983dde8bfb9f798d1beb7c582c66781189

test:
  secret_key_base: 8016cff1b5fb1d2fba24356d560008147a6d6684de031f311f63382aab68c4b796608a3f78a00e69f354fa60661f7ee840b5bdbc7d368a96e399c009629947be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
